package com.example.pokedex.activity.activity;

import com.example.pokedex.R;

class Data {


    String[] nome = new String[]{
            "Bulbasaur",
            "Ivysaur",
            "Venusaur",
            "Charmander",
            "Charmeleon",
            "Charizard",
            "Squirtle",
            "Wartortle",
            "Blastoise",
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Pidgey",
            "Pidgeotto",
            "Pidgeot",
            "Rattata",
            "Raticate",
            "Spearow",
            "Fearow",
            "Ekans",
            "Arbok",
            "Pikachu",
            "Raichu",
            "Sandshrew",
            "Sandslash",
            "Nidoran Fêmea",
            "Nidorina",
            "Nidoqueen",
            "Nidoran Macho",
            "Nidorino",
            "Nidoking",
            "Clefairy",
            "Clefable",
            "Vulpix",
            "Ninetales",
            "Jigglypuff",
            "Wigglytuff",
            "Zubat",
            "Golbat",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Paras",
            "Parasect",
            "Venonat",
            "Venomoth",
            "Diglett",
            "Dugtrio",
            "Meowth",
            "Persian",
            "Psyduck",
            "Golduck",
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Poliwag",
            "Poliwhirl",
            "Poliwrath",
            "Abra",
            "Kadabra",
            "Alakazam",
            "Machop",
            "Machoke",
            "Machamp",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Tentacool",
            "Tentacruel",
            "Geodude",
            "Graveler",
            "Golem",
            "Ponyta",
            "Rapidash",
            "Slowpoke",
            "Slowbro",
            "Magnemite",
            "Magneton",
            "Farfetch'd",
            "Doduo",
            "Dodrio",
            "Seel",
            "Dewgong",
            "Grimer",
            "Muk",
            "Shellder",
            "Cloyster",
            "Gastly",
            "Haunter",
            "Gengar",
            "Onix",
            "Drowzee",
            "Hypno",
            "Krabby",
            "Kingler",
            "Voltorb",
            "Electrode",
            "Exeggcute",
            "Exeggutor",
            "Cubone",
            "Marowak",
            "Hitmonlee",
            "Hitmonchan",
            "Lickitung",
            "Koffing",
            "Weezing",
            "Rhyhorn",
            "Rhydon",
            "Chansey",
            "Tangela",
            "Kangaskhan",
            "Horsea",
            "Seadra",
            "Goldeen",
            "Seaking",
            "Staryu",
            "Starmie",
            "Mr. Mime",
            "Scyther",
            "Jynx",
            "Electabuzz",
            "Magmar",
            "Pinsir",
            "Tauros",
            "Magikarp",
            "Gyarados",
            "Lapras",
            "Ditto",
            "Eevee",
            "Vaporeon",
            "Jolteon",
            "Flareon",
            "Porygon",
            "Omanyte",
            "Omastar",
            "Kabuto",
            "Kabutops",
            "Aerodactyl",
            "Snorlax",
            "Articuno",
            "Zapdos",
            "Moltres",
            "Dratini",
            "Dragonair",
            "Dragonite",
            "Mewtwo",
            "Mew"
    };

    int[] foto = new int[]{
            R.drawable.pokemon001,
            R.drawable.pokemon002,
            R.drawable.pokemon003,
            R.drawable.pokemon004,
            R.drawable.pokemon005,
            R.drawable.pokemon006,
            R.drawable.pokemon007,
            R.drawable.pokemon008,
            R.drawable.pokemon009,
            R.drawable.pokemon010,
            R.drawable.pokemon011,
            R.drawable.pokemon012,
            R.drawable.pokemon013,
            R.drawable.pokemon014,
            R.drawable.pokemon015,
            R.drawable.pokemon016,
            R.drawable.pokemon017,
            R.drawable.pokemon018,
            R.drawable.pokemon019,
            R.drawable.pokemon020,
            R.drawable.pokemon021,
            R.drawable.pokemon022,
            R.drawable.pokemon023,
            R.drawable.pokemon024,
            R.drawable.pokemon025,
            R.drawable.pokemon026,
            R.drawable.pokemon027,
            R.drawable.pokemon028,
            R.drawable.pokemon029,
            R.drawable.pokemon030,
            R.drawable.pokemon031,
            R.drawable.pokemon032,
            R.drawable.pokemon033,
            R.drawable.pokemon034,
            R.drawable.pokemon035,
            R.drawable.pokemon036,
            R.drawable.pokemon037,
            R.drawable.pokemon038,
            R.drawable.pokemon039,
            R.drawable.pokemon040,
            R.drawable.pokemon041,
            R.drawable.pokemon042,
            R.drawable.pokemon043,
            R.drawable.pokemon044,
            R.drawable.pokemon045,
            R.drawable.pokemon046,
            R.drawable.pokemon047,
            R.drawable.pokemon048,
            R.drawable.pokemon049,
            R.drawable.pokemon050,
            R.drawable.pokemon051,
            R.drawable.pokemon052,
            R.drawable.pokemon053,
            R.drawable.pokemon054,
            R.drawable.pokemon055,
            R.drawable.pokemon056,
            R.drawable.pokemon057,
            R.drawable.pokemon058,
            R.drawable.pokemon059,
            R.drawable.pokemon060,
            R.drawable.pokemon061,
            R.drawable.pokemon062,
            R.drawable.pokemon063,
            R.drawable.pokemon064,
            R.drawable.pokemon065,
            R.drawable.pokemon066,
            R.drawable.pokemon067,
            R.drawable.pokemon068,
            R.drawable.pokemon069,
            R.drawable.pokemon070,
            R.drawable.pokemon071,
            R.drawable.pokemon072,
            R.drawable.pokemon073,
            R.drawable.pokemon074,
            R.drawable.pokemon075,
            R.drawable.pokemon076,
            R.drawable.pokemon077,
            R.drawable.pokemon078,
            R.drawable.pokemon079,
            R.drawable.pokemon080,
            R.drawable.pokemon081,
            R.drawable.pokemon082,
            R.drawable.pokemon083,
            R.drawable.pokemon084,
            R.drawable.pokemon085,
            R.drawable.pokemon086,
            R.drawable.pokemon087,
            R.drawable.pokemon088,
            R.drawable.pokemon089,
            R.drawable.pokemon090,
            R.drawable.pokemon091,
            R.drawable.pokemon092,
            R.drawable.pokemon093,
            R.drawable.pokemon094,
            R.drawable.pokemon095,
            R.drawable.pokemon096,
            R.drawable.pokemon097,
            R.drawable.pokemon098,
            R.drawable.pokemon099,
            R.drawable.pokemon100,
            R.drawable.pokemon101,
            R.drawable.pokemon102,
            R.drawable.pokemon103,
            R.drawable.pokemon104,
            R.drawable.pokemon105,
            R.drawable.pokemon106,
            R.drawable.pokemon107,
            R.drawable.pokemon108,
            R.drawable.pokemon109,
            R.drawable.pokemon110,
            R.drawable.pokemon111,
            R.drawable.pokemon112,
            R.drawable.pokemon113,
            R.drawable.pokemon114,
            R.drawable.pokemon115,
            R.drawable.pokemon116,
            R.drawable.pokemon117,
            R.drawable.pokemon118,
            R.drawable.pokemon119,
            R.drawable.pokemon120,
            R.drawable.pokemon121,
            R.drawable.pokemon122,
            R.drawable.pokemon123,
            R.drawable.pokemon124,
            R.drawable.pokemon125,
            R.drawable.pokemon126,
            R.drawable.pokemon127,
            R.drawable.pokemon128,
            R.drawable.pokemon129,
            R.drawable.pokemon130,
            R.drawable.pokemon131,
            R.drawable.pokemon132,
            R.drawable.pokemon133,
            R.drawable.pokemon134,
            R.drawable.pokemon135,
            R.drawable.pokemon136,
            R.drawable.pokemon137,
            R.drawable.pokemon138,
            R.drawable.pokemon139,
            R.drawable.pokemon140,
            R.drawable.pokemon141,
            R.drawable.pokemon142,
            R.drawable.pokemon143,
            R.drawable.pokemon144,
            R.drawable.pokemon145,
            R.drawable.pokemon146,
            R.drawable.pokemon147,
            R.drawable.pokemon148,
            R.drawable.pokemon149,
            R.drawable.pokemon150,
            R.drawable.pokemon151
    };

    String[] tipo = {
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Fogo",
            "Fogo",
            "Fogo, Voador",
            "Água",
            "Água",
            "Água",
            "Inseto",
            "Inseto",
            "Inseto, Voador",
            "Inseto, Venenoso",
            "Inseto, Venenoso",
            "Inseto, Venenoso",
            "Normal, Voador",
            "Normal, Voador",
            "Normal, Voador",
            "Normal",
            "Normal",
            "Normal, Voador",
            "Normal, Voador",
            "Venenoso",
            "Venenoso",
            "Elétrico",
            "Elétrico",
            "Terrestre",
            "Terrestre",
            "Venenoso",
            "Venenoso",
            "Venenoso, Terrestre",
            "Venenoso",
            "Venenoso",
            "Venenoso, Terrestre",
            "Fada",
            "Fada",
            "Fogo",
            "Fogo",
            "Fada, Normal",
            "Fada, Normal",
            "Venenoso, Voador",
            "Venenoso, Voador",
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Inseto, Grama",
            "Inseto, Grama",
            "Inseto, Venenoso",
            "Inseto, Venenoso",
            "Terrestre",
            "Terrestre",
            "Normal",
            "Normal",
            "Água, Psyquico",
            "Água, Psyquico",
            "Lutador",
            "Lutador",
            "Fogo",
            "Fogo",
            "Água",
            "Água",
            "Água, Lutador",
            "Psyquico",
            "Psyquico",
            "Psyquico",
            "Lutador",
            "Lutador",
            "Lutador",
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Grama, Venenoso",
            "Água, Venenoso",
            "Água, Venenoso",
            "Pedra, Terrestre",
            "Pedra, Terrestre",
            "Pedra, Terrestre",
            "Fogo",
            "Fogo",
            "Água, Psyquico",
            "Água, Psyquico",
            "Elétrico, Metal",
            "Elétrico, Metal",
            "Normal, Voador",
            "Normal, Voador",
            "Normal, Voador",
            "Água",
            "Água, Gelo",
            "Venenoso",
            "Venenoso",
            "Água",
            "Água, Gelo",
            "Fantasma, Venenoso",
            "Fantasma, Venenoso",
            "Fantasma, Venenoso",
            "Pedra, Terrestre",
            "Psyquico",
            "Psyquico",
            "Água",
            "Água",
            "Elétrico",
            "Elétrico",
            "Grama, Psyquico",
            "Grama, Psyquico",
            "Terrestre",
            "Terrestre",
            "Lutador",
            "Lutador",
            "Normal",
            "Venenoso",
            "Venenoso",
            "Terrestre, Pedra",
            "Terrestre, Pedra",
            "Normal",
            "Grama",
            "Normal",
            "Água",
            "Água",
            "Água",
            "Água",
            "Água",
            "Água, Psyquico",
            "Psyquico",
            "Inseto, Voador",
            "Gelo, Psyquico",
            "Elétrico",
            "Fogo",
            "Inseto",
            "Normal",
            "Água",
            "Água, Voador",
            "Água, Gelo",
            "Normal",
            "Normal",
            "Água",
            "Elétrico",
            "Fogo",
            "Normal",
            "Pedra, Água",
            "Pedra, Água",
            "Pedra, Água",
            "Pedra, Água",
            "Pedra, Voador",
            "Normal",
            "Gelo, Voador",
            "Elétrico, Voador",
            "Fogo, Voador",
            "Dragão",
            "Dragão",
            "Dragão, Voador",
            "Psyquico",
            "Psyquico"
    };
}
